server {
    listen 80;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    autoindex on;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location ~* \.(jpg|jpeg|png|gif|webp|svg|ico)$ {
        expires 1h;
        add_header Cache-Control "public, max-age=3600";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
